const MyFuntion = () => {
    try {
        const Name = "Hello World";
        alert(Name);
    } catch (error) {
        alert(error.message);
    }
}

MyFuntion();